### ISSUE TITLE
Errors reported by rake task during install

### ISSUE THREAD

**Issue by jrsmith2002** [hidakatsuya/redmine_default_custom_query#35]
When I run the following rake task, when installing this plugin
rake redmine:plugins:migrate NAME=redmine_default_custom_query RAILS_ENV=production

I get the following errors:

rake aborted!
NameError: uninitialized constant DefaultCustomQueryHelper
/var/www/...../plugins/redmine_default_custom_query-1.3.0/lib/default_custom_query.rb:14:in `block in '
/var/www/...../vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `instance_exec'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `block in simple'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:50:in `block in '
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/var/www/...../config/environment.rb:14:in `'
/var/www/...../plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `'
/var/www/...../lib/tasks/redmine.rake:194:in `block in '
/var/www/...../lib/tasks/redmine.rake:194:in `each'
/var/www/...../lib/tasks/redmine.rake:194:in `'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `each'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `run_tasks_blocks'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:452:in `run_tasks_blocks'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:453:in `load_tasks'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/var/www/...../Rakefile:7:in `'
/var/www/...../vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `'
(See full trace by running task with --trace)

Is there anything else you need to know from me?

Kind regards,

Jonathan

**Comment by jrsmith2002** [comment]
sorry - I see my error - wrong directory name in plugins folder
