### ISSUE TITLE
Conflict with DMS plugin

### ISSUE THREAD

**Issue by PavelBaco** [hidakatsuya/redmine_default_custom_query#37]
Hi, thank you for your work, i really want use your plugin but i have conflict with another one.

Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"centralni-evidence-ukolu"}
  Current user: admin (id=1)
  Rendered projects/settings.html.erb within layouts/base (144.3ms)
Completed 500 Internal Server Error in 157ms (ActiveRecord: 4.1ms)

ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x0055e57d92cc88>:0x0055e57d92c288>
Did you mean?  project_settings_tabs_with_project_tab):
    1: <h2><%=l(:label_settings)%></h2>
    2:
    3: <%= render_tabs project_settings_tabs %>
    4:
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  plugins/redmine_default_custom_query/app/patches/helpers/projects_helper_patch.rb:13:in `project_settings_tabs_with_default_query_setting_tab'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__2358237997190216469_70074762436920'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'

Is there any chance to fix it?

**Comment by iq2luc** [comment]
```
F, [2019-06-21T12:32:32.993826 #23235] FATAL -- :
ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x00000007e602b0>:0x00000007b39398>
Did you mean?  project_issues_path):
    1: <h2><%=l(:label_settings)%></h2>
    2:
    3: <%= render_tabs project_settings_tabs %>
    4:
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  plugins/redmine_default_custom_query/app/patches/helpers/projects_helper_patch.rb:13:in `project_settings_tabs_with_default_query_setting_tab'
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___2916392239599526829_77182800'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'
```

**Comment by maeda-m** [comment]
Thank you for the report.

Maybe this is not a bug in DefaultCustomQuery. I think that it is a coding mistake of other plug-ins.
An error occurs if the following code exists:

https://github.com/danmunn/redmine_dmsf/blob/1d63ce0ee72d8cd723448d6a21000e5486bbb3c8/lib/redmine_dmsf/patches/projects_helper_patch.rb#L29

This is not an appropriate code for module (patch) to include to ProjectsHelper.

Although it is described in the DMSF CHANGELOG as follows, it is preferable that we do not call super which is not present in class by alias_method etc.

https://github.com/danmunn/redmine_dmsf/blob/master/CHANGELOG.md#161-2018-04-03

Thanks.

**Comment by iq2luc** [comment]
Thank you @maeda-m for looking into it.
I guess this issue may be closed then.
I opened an [issue on DMSF side](https://github.com/danmunn/redmine_dmsf/issues/1020#issue-464537059).

**Comment by maeda-m** [comment]
Thank you for the report.
Released [version 1.5.0](https://github.com/hidakatsuya/redmine_default_custom_query/releases/tag/1.5.0) !
