### ISSUE TITLE
Redmine 5.x

### ISSUE THREAD

**Issue by AlexShku** [hidakatsuya/redmine_default_custom_query#51]
Hello! 
Are you planning to adapt your plugin for Redmine 5.x?

**Comment by ryhoo2** [comment]
Any chance for support of Redmine 5.1.x?


I get the following error during plugin migration operation:

_rake aborted!
Zeitwerk::NameError: expected file /var/www/redmine/plugins/redmine_default_custom_query/app/hooks/issues_controller_hook.rb to define constant IssuesControllerHook, but didn't
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/callbacks.rb:33:in `on_file_autoloaded'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:31:in `require'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies/zeitwerk_integration.rb:51:in `require_dependency'
/var/www/redmine/plugins/redmine_default_custom_query/lib/default_custom_query.rb:20:in `block in <top (required)>'
/var/www/redmine/plugins/redmine_default_custom_query/lib/default_custom_query.rb:20:in `each'
/var/www/redmine/plugins/redmine_default_custom_query/lib/default_custom_query.rb:20:in `<top (required)>'
/var/www/redmine/plugins/redmine_default_custom_query/init.rb:15:in `require_relative'
/var/www/redmine/plugins/redmine_default_custom_query/init.rb:15:in `<top (required)>'
/var/www/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/var/www/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/var/www/redmine/lib/redmine/plugin_loader.rb:108:in `each'
/var/www/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:427:in `instance_exec'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:603:in `catch'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:199:in `block in halting'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:512:in `each'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:512:in `invoke_before'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:105:in `run_callbacks'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/reloader.rb:88:in `prepare!'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `instance_exec'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `run'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:60:in `run_initializers'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/application.rb:391:in `initialize!'
/var/www/redmine/config/environment.rb:16:in `<top (required)>'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `block in require'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `require'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/application.rb:367:in `require_environment!'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
rake aborted!
Zeitwerk::NameError: expected file /var/www/redmine/plugins/redmine_default_custom_query/app/hooks/issues_controller_hook.rb to define constant IssuesControllerHook, but didn't
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/callbacks.rb:33:in `on_file_autoloaded'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:31:in `require'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies/zeitwerk_integration.rb:51:in `require_dependency'
/var/www/redmine/plugins/redmine_default_custom_query/lib/default_custom_query.rb:20:in `block in <top (required)>'
/var/www/redmine/plugins/redmine_default_custom_query/lib/default_custom_query.rb:20:in `each'
/var/www/redmine/plugins/redmine_default_custom_query/lib/default_custom_query.rb:20:in `<top (required)>'
/var/www/redmine/plugins/redmine_default_custom_query/init.rb:15:in `require_relative'
/var/www/redmine/plugins/redmine_default_custom_query/init.rb:15:in `<top (required)>'
/var/www/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/var/www/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/var/www/redmine/lib/redmine/plugin_loader.rb:108:in `each'
/var/www/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:427:in `instance_exec'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:603:in `catch'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:199:in `block in halting'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:512:in `each'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:512:in `invoke_before'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:105:in `run_callbacks'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/reloader.rb:88:in `prepare!'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `instance_exec'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `run'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/initializable.rb:60:in `run_initializers'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/application.rb:391:in `initialize!'
/var/www/redmine/config/environment.rb:16:in `<top (required)>'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `block in require'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `require'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/application.rb:367:in `require_environment!'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.6/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)_
